#ifndef QCONTROLSO_GLOBAL_H
#define QCONTROLSO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCONTROLSO_LIBRARY)
#  define QCONTROLSOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QCONTROLSOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QCONTROLSO_GLOBAL_H
