#ifndef QDATABASESO_GLOBAL_H
#define QDATABASESO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QDATABASESO_LIBRARY)
#  define QDATABASESOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QDATABASESOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QDATABASESO_GLOBAL_H
